name: Build deploy TST

on:
  workflow_dispatch:
      inputs:
        manual_deploy:
          description: "Manual Deploy"
          required: true
          type: boolean
          default: true
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set color
        id: color-selector
        run: |
          output="Service URL: https://run-4i-tst-4casthub-faas-workers-nvykd5ypmq-ue.a.run.app"
          url=$(echo "$output" | grep -oP 'https?://[^\s]+')
          echo "SELECTED_COLOR=$url" >> "$GITHUB_OUTPUT"
        
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "$SELECTED_COLOR"